config/routes.rb
Rails.application.routes.draw do

  resources :blurbs do
    resources :comments
    resources :likes
  end

  get 'sessions/new'
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
  resources :searches, only: [:index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'blurbs#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'tags/:tag', to: 'articles#index', as: :tag
end

app/models/blurb.rb
class Blurb < ApplicationRecord
  
  ActiveSupport.on_load :action_text_rich_text do
    include PgSearch::Model
    multisearchable against: :body

    belongs_to :user

    before_save { content.plain_text_body = content.body.to_plain_text }

    scope :with_content_containing, ->(query) { joins(:rich_text_content).merge(ActionText::RichText.with_body_containing(query)) }

    has_one_attached :picture
    has_rich_text :body

    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy

    validates :body, length: { minimum: 1, maximum: 1000 }

    def liked_by?(liking_user)
      like_for_user(liking_user).present?
    end

    def like_for_user(liking_user)
      return if liking_user.nil?

      likes.find_by_user_id(liking_user.id)
    end
  end
  attr_accessible :body, :name, :tag_list
  acts_as_taggable
end

app/controllers/blurbs_controller.rb
class BlurbsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :require_author, only: [:edit, :update, :destroy]
  before_action :require_user_login, except: [:show, :index]

  def create
    @blurb = current_user.blurbs.new(blurb_params)
    if @blurb.save
      redirect_to blurbs_path, info: "Post was successfully created"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def new
    @blurb = current_user.blurbs.new
  end

  def index
    @blurbs = Blurb.all

    if params[:tag]
      @articles = Article.tagged_with(params[:tag])
    else
      @articles = Article.all
    end
  end

  # def show
  #   @posts = Post.find(params[:id])
  # end
  def update
    @blurb = current_user.blurbs.find(params[:id])

    if @blurb.update(blurb_params)
      redirect_to @blurb, notice: "Post was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def show
  end

  def destroy
    @blurb = current_user.blurbs.find(params[:id])
    @blurb.destroy
    flash[:success] = 'Post was successfully destroyed!'
    redirect_to root_path
  end

  def edit
    @blurb = current_user.blurbs.find(params[:id])
  end

  def require_user_login
    if current_user.nil?
      flash[:notice] = 'YOU MUST BE LOGGED IN'
      redirect_to login_path
    end
  end

  private

  def set_post
    @blurb = Blurb.find(params[:id])
  end

  def require_author
    redirect_to(root_path) unless @blurb.user == current_user
  end

  def blurb_params
    params.require(:blurb).permit(:name, :body, :picture)
  end

end

app/helpers/blurbs_helper.rb
module BlurbsHelper
end

app/views/blurbs/_blurb.html.erb
<div class="card border border-dark border-1">
  <div class="card-body">

    <%= link_to blurb.user.username, blurb.user, class: 'nav-link' %>

    <%# --------------------ADD IMAGE------------------------- %>
    <% if blurb.picture.attached? %>          
      <%= image_tag(blurb.picture, style:'width:400px; height:300px' ) %>
    <% end %> 

    <div class="">
      <p class="fs-5"> BLURBER:<%= blurb.body %></p>
    </div>
    <%# ---------------------BLURB POST------------------------- %>
    <% if  blurb.body %>
      <%= button_to " Discard ", blurb_path(blurb), method: :delete, class: 'btn btn-outline-danger' %>
      <%= button_to "COMMENT", new_blurb_comment_path(blurb), method: :get, class: "btn btn-outline-info" %>


      <%# ---------------------LIKE FUNCTION------------------------- %>
      <p><%= blurb.likes.count %> </p>

      <% like = blurb.like_for_user(current_user) %>
      <% if like %>
        <%= button_to 'unlike', blurb_like_path(blurb, like), method: :delete %>
      <% else %>
        <%= button_to 'like', blurb_likes_path(blurb), method: :post %>
      <% end %>
    <% end %>


    <span class="timestamp">
      Posted <%= time_ago_in_words(blurb.created_at) %> ago.
    </span>

    <% if blurb.comments.any?  %>

      <% blurb.comments.each do |comment| %>
        <p class='text-uppercase'>Comments:</p>
        <h2 class='fs-5 fw-bold'> <%= comment.user.name %> </h2>
        <p class='fs-6'><%= comment.bloob %></p>
      <% end %>
    <% end %>

  </div>
</div>

app/views/blurbs/_form.html.erb
<%= form_with(model: blurb ) do |b| %>

  <div class="form-input">
    <%= b.label :body %>
    <%= b.rich_text_area :body, class:'form-control' %>
  </div>


  <div class='mb-3 mt-4p'>
    <%= b.submit 'Add Post', class: "btn btn-outline-success mb-5 mt-5" %>
  </div>

  <div class="field">
    <%= f.label :tag_list, "Tags (separated by commas)" %><br />
    <%= f.text_field :tag_list %>
  </div>

  <div class="field mt-5">
    <%= b.label :picture %>
    <p>Add pictures here</p><%= b.file_field :picture %>
  </div>

<% end %>

app/views/blurbs/index.html.erb
INDEX

<div class='text-center'>
  <% if @blurbs.any? %>
    <%# <%= render @posts %> 
    <%= render partial: "blurb", collection: @blurbs %>
  <% else %>
    <p>Sorry no BLURBS here, but why not create one</p>
    <%= button_to "Create Blurb!", '/blurbs/new', method: :get, class: 'btn btn-info' %>
  <% end %>
</div>

app/views/blurbs/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-8 offset-2"> 
      <div class='text-center'>
        <% if current_user %>
          <%= render partial: 'form', locals: { blurb: @blurb } %>
        <% else %>
          <h1>NEED TO BE SIGNED IN TO CREATE BLURBS!! </h1>
        <% end %>
      </div>
    </div>
  </div>
</div>