config/routes.rb
Rails.application.routes.draw do

  resources :blurbs do
    resources :comments
    resources :likes
  end

  get 'sessions/new'
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
  resources :searches, only: [:index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'blurbs#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'tags/:tag', to: 'articles#index', as: :tag
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blurbs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class='bg-white'>
    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
          <a class="navbar-brand" href="#">BLURBS</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
            
              <% if current_user %>
                  Hi <%= current_user.name %>

                  <%= link_to "Sign Out", logout_path, data: {turbo_method: :delete}, class: 'nav-link mx-3' %>
                  <%= link_to "My profile", users_path(current_user), method: :get, class: 'nav-link mx-3' %>
                  <%= link_to "Create Blurb!", '/blurbs/new', method: :get, class: 'nav-link mx-3' %>
                  <%= link_to "Edit Profile ", edit_user_path(current_user), method: :get, class:'nav-link mx-3' %>
                  <section class="stats">
                    <%= render 'shared/stats' %>
                  </section>


              <% else %>
                <%= link_to 'Log in', login_path, method: :get, class:'nav-link mx-3' %>

                <%= link_to 'Sign up', new_user_path, method: :get, class:'nav-link mx-3' %>
              <% end %>
              <%= link_to 'Home', root_path, method: :get, class:'nav-link mx-3'%>

              <%= form_tag(searches_path, method: :get) do %>
                <%= text_field_tag(:search, params[:name]) %>
                <%= submit_tag ('Search') %>
              <% end %>

            </div>
          </div>
        </div>
    </nav>








    <%= yield %>
  </body>
</html>